<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>files</key>
	<dict>
		<key>Resources/16.png</key>
		<data>
		B4XSeWbhVnntYnSiTkQo3r2TrBw=
		</data>
		<key>Resources/Credits.html</key>
		<data>
		XGwrcEjzQWWu1f9IOyYzTv3ldro=
		</data>
		<key>Resources/MainWin.nib</key>
		<data>
		BxQxCn5HmffqaqO/THVqOccgj1A=
		</data>
		<key>Resources/about.png</key>
		<data>
		JpLY+wREFWU4M6omCqAMWr56ip4=
		</data>
		<key>Resources/big_arrow.png</key>
		<data>
		U0Ahn/CKZar2MEuJejisaL3Neeo=
		</data>
		<key>Resources/en.lproj/InfoPlist.strings</key>
		<dict>
			<key>hash</key>
			<data>
			MiLKDDnrUKr4EmuvhS5VQwxHGK8=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>Resources/en.lproj/MainMenu.nib</key>
		<dict>
			<key>hash</key>
			<data>
			od18HvBsk3GNCH22h+q+T90+wwM=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>Resources/icon.icns</key>
		<data>
		JTGhevqcNxIw5e7twIXrneRnW1U=
		</data>
	</dict>
	<key>rules</key>
	<dict>
		<key>^Resources/</key>
		<true/>
		<key>^Resources/.*\.lproj/</key>
		<dict>
			<key>optional</key>
			<true/>
			<key>weight</key>
			<real>1000</real>
		</dict>
		<key>^Resources/.*\.lproj/locversion.plist$</key>
		<dict>
			<key>omit</key>
			<true/>
			<key>weight</key>
			<real>1100</real>
		</dict>
		<key>^_MASReceipt/</key>
		<dict>
			<key>omit</key>
			<true/>
			<key>weight</key>
			<real>1000</real>
		</dict>
		<key>^version.plist$</key>
		<true/>
	</dict>
</dict>
</plist>
